# Generated by Django 5.1.4 on 2025-02-13 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_category'),
        ('users', '0002_remove_otpstorage_otp_remove_user_completed_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpstorage',
            name='otp_hash',
        ),
        migrations.AddField(
            model_name='otpstorage',
            name='otp',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='otpstorage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
